-- H2 인메모리 DB용 테스트 스키마 (V1~V27 마이그레이션 반영)
-- PostgreSQL 전용 타입/구문을 H2 호환으로 대체

-- paper_trading 스키마 생성
CREATE SCHEMA IF NOT EXISTS paper_trading;

-- ── 기본 스키마 테이블 ────────────────────────────────────────────────────────

-- 캔들 데이터
CREATE TABLE IF NOT EXISTS candle_data (
    time        TIMESTAMP       NOT NULL,
    coin_pair   VARCHAR(20)     NOT NULL,
    timeframe   VARCHAR(10)     NOT NULL,
    open        DECIMAL(20, 8)  NOT NULL,
    high        DECIMAL(20, 8)  NOT NULL,
    low         DECIMAL(20, 8)  NOT NULL,
    close       DECIMAL(20, 8)  NOT NULL,
    volume      DECIMAL(30, 8)  NOT NULL,
    PRIMARY KEY (time, coin_pair, timeframe)
);

-- 시장 데이터 캐시 (V13)
CREATE TABLE IF NOT EXISTS market_data_cache (
    time        TIMESTAMP       NOT NULL,
    coin_pair   VARCHAR(20)     NOT NULL,
    timeframe   VARCHAR(10)     NOT NULL,
    open        DECIMAL(20, 8)  NOT NULL,
    high        DECIMAL(20, 8)  NOT NULL,
    low         DECIMAL(20, 8)  NOT NULL,
    close       DECIMAL(20, 8)  NOT NULL,
    volume      DECIMAL(20, 8)  NOT NULL,
    PRIMARY KEY (time, coin_pair, timeframe)
);

-- 백테스트 실행 기록 (V2)
CREATE TABLE IF NOT EXISTS backtest_run (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name        VARCHAR(50)     NOT NULL,
    coin_pair            VARCHAR(20)     NOT NULL,
    timeframe            VARCHAR(10)     NOT NULL,
    start_date           TIMESTAMP       NOT NULL,
    end_date             TIMESTAMP       NOT NULL,
    initial_capital      DECIMAL(20, 2)  NOT NULL,
    slippage_pct         DECIMAL(10, 4),
    fee_pct              DECIMAL(10, 4),
    config_json          CLOB            NOT NULL DEFAULT '{}',
    fill_simulation_json CLOB,
    is_walk_forward      BOOLEAN,
    wf_in_sample         TIMESTAMP,
    wf_out_sample        TIMESTAMP,
    created_at           TIMESTAMP
);

-- 백테스트 성과 지표 (V2)
CREATE TABLE IF NOT EXISTS backtest_metrics (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_run_id      BIGINT          NOT NULL,
    total_return_pct     DECIMAL(10, 4),
    win_rate_pct         DECIMAL(10, 4),
    mdd_pct              DECIMAL(10, 4),
    sharpe_ratio         DECIMAL(10, 4),
    sortino_ratio        DECIMAL(10, 4),
    calmar_ratio         DECIMAL(10, 4),
    win_loss_ratio       DECIMAL(10, 4),
    recovery_factor      DECIMAL(10, 4),
    total_trades         INTEGER,
    winning_trades       INTEGER,
    losing_trades        INTEGER,
    avg_profit_pct       DECIMAL(10, 4),
    avg_loss_pct         DECIMAL(10, 4),
    max_consecutive_loss INTEGER,
    monthly_returns_json CLOB,
    segment              VARCHAR(20)
);

-- 백테스트 개별 거래 내역 (V2)
CREATE TABLE IF NOT EXISTS backtest_trade (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_run_id BIGINT          NOT NULL,
    side            VARCHAR(4)      NOT NULL,
    price           DECIMAL(20, 8)  NOT NULL,
    quantity        DECIMAL(20, 8)  NOT NULL,
    fee             DECIMAL(20, 8),
    slippage        DECIMAL(20, 8),
    pnl             DECIMAL(20, 8),
    cumulative_pnl  DECIMAL(20, 8),
    signal_reason   TEXT,
    market_regime   VARCHAR(20),
    executed_at     TIMESTAMP       NOT NULL
);

-- 전략 설정 (V3 + V11)
CREATE TABLE IF NOT EXISTS strategy_config (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    strategy_type   VARCHAR(50)     NOT NULL,
    coin_pair       VARCHAR(20)     NOT NULL,
    timeframe       VARCHAR(10)     NOT NULL,
    config_json     CLOB            NOT NULL DEFAULT '{}',
    is_active       BOOLEAN,
    manual_override BOOLEAN         NOT NULL DEFAULT FALSE,
    max_investment  DECIMAL(20, 2),
    stop_loss_pct   DECIMAL(10, 4),
    reinvest_pct    DECIMAL(10, 4),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

-- 리스크 설정 (V5 + V24)
CREATE TABLE IF NOT EXISTS risk_config (
    id                       BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_daily_loss_pct       DECIMAL(5, 2)   DEFAULT 3.0,
    max_weekly_loss_pct      DECIMAL(5, 2)   DEFAULT 7.0,
    max_monthly_loss_pct     DECIMAL(5, 2)   DEFAULT 15.0,
    max_positions            INTEGER         DEFAULT 3,
    cooldown_minutes         INTEGER         DEFAULT 60,
    portfolio_limit_krw      DECIMAL(20, 2),
    mdd_threshold_pct        DECIMAL(5, 2)   DEFAULT 20.0,
    consecutive_loss_limit   INTEGER         DEFAULT 5,
    circuit_breaker_enabled  BOOLEAN         DEFAULT TRUE,
    updated_at               TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- 실전매매 세션 (V12 + V19 + V24)
CREATE TABLE IF NOT EXISTS live_trading_session (
    id                            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_type                 VARCHAR(50)     NOT NULL,
    coin_pair                     VARCHAR(20)     NOT NULL,
    timeframe                     VARCHAR(10)     NOT NULL,
    initial_capital               DECIMAL(20, 2)  NOT NULL,
    available_krw                 DECIMAL(20, 2)  NOT NULL,
    total_asset_krw               DECIMAL(20, 2)  NOT NULL,
    status                        VARCHAR(20)     NOT NULL DEFAULT 'STOPPED',
    strategy_params               CLOB            DEFAULT '{}',
    max_investment                DECIMAL(20, 2),
    stop_loss_pct                 DECIMAL(5, 2)   DEFAULT 5.0,
    invest_ratio                  DECIMAL(5, 4)   NOT NULL DEFAULT 0.8000,
    mdd_peak_capital              DECIMAL(20, 2),
    circuit_breaker_triggered_at  TIMESTAMP,
    circuit_breaker_reason        VARCHAR(255),
    started_at                    TIMESTAMP,
    stopped_at                    TIMESTAMP,
    created_at                    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at                    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- 포지션 (V4 + V22 + V23 + V26 + V29)
CREATE TABLE IF NOT EXISTS position (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_pair           VARCHAR(20)     NOT NULL,
    side                VARCHAR(4)      NOT NULL,
    entry_price         DECIMAL(20, 8)  NOT NULL,
    avg_price           DECIMAL(20, 8)  NOT NULL,
    size                DECIMAL(20, 8)  NOT NULL,
    unrealized_pnl      DECIMAL(20, 8)  DEFAULT 0,
    realized_pnl        DECIMAL(20, 8)  DEFAULT 0,
    strategy_config_id  BIGINT,
    session_id          BIGINT,
    status              VARCHAR(10)     DEFAULT 'OPEN',
    position_fee        DECIMAL(20, 2)  NOT NULL DEFAULT 0,
    stop_loss_price     DECIMAL(20, 8),
    take_profit_price   DECIMAL(20, 8),
    invested_krw        DECIMAL(20, 8),
    opened_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    closing_at          TIMESTAMP,
    closed_at           TIMESTAMP
);

-- 주문 (V4 + V12 + V27 + V28)
CREATE TABLE IF NOT EXISTS "order" (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT,
    position_id         BIGINT,
    coin_pair           VARCHAR(20)     NOT NULL,
    side                VARCHAR(4)      NOT NULL,
    order_type          VARCHAR(10)     NOT NULL,
    price               DECIMAL(20, 8),
    quantity            DECIMAL(20, 8)  NOT NULL,
    state               VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    exchange_order_id   VARCHAR(100),
    filled_quantity     DECIMAL(20, 8)  DEFAULT 0,
    executed_funds      DECIMAL(20, 8),
    signal_reason       TEXT,
    response_json       TEXT,
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    submitted_at        TIMESTAMP,
    filled_at           TIMESTAMP,
    cancelled_at        TIMESTAMP,
    failed_reason       TEXT
);

-- 거래 로그 (V6)
CREATE TABLE IF NOT EXISTS trade_log (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT,
    event_type  VARCHAR(30) NOT NULL,
    old_state   VARCHAR(20),
    new_state   VARCHAR(20),
    detail_json CLOB,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- 전략 신호 (V7 + V25)
CREATE TABLE IF NOT EXISTS strategy_signal (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_config_id  BIGINT,
    coin_pair           VARCHAR(20)     NOT NULL,
    timeframe           VARCHAR(10)     NOT NULL,
    signal              VARCHAR(10)     NOT NULL,
    strength            DECIMAL(5, 2),
    reason              TEXT            NOT NULL,
    indicators_json     CLOB,
    market_regime       VARCHAR(20),
    candle_time         TIMESTAMP       NOT NULL,
    was_executed        BOOLEAN         DEFAULT FALSE,
    created_at          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- 전략 신호 로그 (V6 + V17 + V25)
CREATE TABLE IF NOT EXISTS strategy_log (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name   VARCHAR(50)     NOT NULL,
    coin_pair       VARCHAR(20)     NOT NULL,
    signal          VARCHAR(10),
    reason          TEXT            NOT NULL,
    indicators_json CLOB,
    market_regime   VARCHAR(20),
    session_type    VARCHAR(10)     DEFAULT 'PAPER',
    session_id      BIGINT,
    created_at      TIMESTAMP
);

-- 활성화 전략 테이블 (V14)
CREATE TABLE IF NOT EXISTS strategy_type_enabled (
    strategy_name  VARCHAR(50)  PRIMARY KEY,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 텔레그램 알림 로그 (V16)
CREATE TABLE IF NOT EXISTS telegram_notification_log (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           VARCHAR(30)     NOT NULL,
    session_label  VARCHAR(100),
    message_text   TEXT            NOT NULL,
    success        BOOLEAN         NOT NULL DEFAULT TRUE,
    sent_at        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 백테스트 비동기 작업 상태 (V30)
CREATE TABLE IF NOT EXISTS backtest_job (
    id               BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type         VARCHAR(20)     NOT NULL,
    status           VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    coin_pair        VARCHAR(20),
    strategy_name    VARCHAR(200),
    timeframe        VARCHAR(10),
    request_json     TEXT,
    total_candles    INTEGER,
    total_chunks     INTEGER,
    completed_chunks INTEGER         NOT NULL DEFAULT 0,
    backtest_run_id  BIGINT,
    error_message    TEXT,
    created_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── paper_trading 스키마 테이블 ────────────────────────────────────────────────

-- 모의투자 세션 (V8 + V9 + V10 + V15 + V18 + V21)
CREATE TABLE IF NOT EXISTS paper_trading.virtual_balance (
    id               BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_krw        DECIMAL(20, 2)  NOT NULL,
    available_krw    DECIMAL(20, 2)  NOT NULL,
    initial_capital  DECIMAL(20, 2),
    strategy_name    VARCHAR(50),
    coin_pair        VARCHAR(20),
    timeframe        VARCHAR(10),
    status           VARCHAR(10)     NOT NULL,
    telegram_enabled BOOLEAN         NOT NULL DEFAULT FALSE,
    realized_pnl     DECIMAL(20, 2)  NOT NULL DEFAULT 0,
    total_fee        DECIMAL(20, 2)  NOT NULL DEFAULT 0,
    version          BIGINT          NOT NULL DEFAULT 0,
    started_at       TIMESTAMP,
    stopped_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

-- 모의투자 포지션 (V8 + V10 + V20 + V26)
CREATE TABLE IF NOT EXISTS paper_trading.position (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_pair           VARCHAR(20)     NOT NULL,
    side                VARCHAR(4)      NOT NULL,
    entry_price         DECIMAL(20, 8)  NOT NULL,
    avg_price           DECIMAL(20, 8)  NOT NULL,
    size                DECIMAL(20, 8)  NOT NULL,
    unrealized_pnl      DECIMAL(20, 8),
    realized_pnl        DECIMAL(20, 8),
    strategy_config_id  BIGINT,
    session_id          BIGINT,
    status              VARCHAR(10),
    position_fee        DECIMAL(20, 2)  NOT NULL DEFAULT 0,
    stop_loss_price     DECIMAL(20, 8),
    take_profit_price   DECIMAL(20, 8),
    opened_at           TIMESTAMP,
    closed_at           TIMESTAMP
);

-- 모의투자 주문 (V8 + V10)
CREATE TABLE IF NOT EXISTS paper_trading."order" (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT,
    position_id         BIGINT,
    coin_pair           VARCHAR(20)     NOT NULL,
    side                VARCHAR(4)      NOT NULL,
    order_type          VARCHAR(10)     NOT NULL,
    price               DECIMAL(20, 8),
    quantity            DECIMAL(20, 8)  NOT NULL,
    state               VARCHAR(20)     NOT NULL,
    exchange_order_id   VARCHAR(100),
    filled_quantity     DECIMAL(20, 8),
    signal_reason       TEXT,
    created_at          TIMESTAMP,
    submitted_at        TIMESTAMP,
    filled_at           TIMESTAMP,
    cancelled_at        TIMESTAMP,
    failed_reason       TEXT
);
